# prometheus.yml

global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'flux_server'
    static_configs:
      - targets: ['localhost:8000']




global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'django'
    static_configs:
      - targets: ['backend:8000']




global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'django'
    static_configs:
      - targets: ['localhost:8000']



global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'flux_backend'
    static_configs:
      - targets: ['flux_backend:8000']

  - job_name: 'flux_db'
    static_configs:
      - targets: ['flux_db:5432']
