



version: '3.8'
services:
  backend:
    build: ./src/backend
    env_file: ./config/environments/development.env
    ports:
      - "8000:8000"
    depends_on:
      - db
  db:
    image: postgres
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"



version: '3.8'

services:
  backend:
    build:
      context: ../src/backend
      dockerfile: Dockerfile
    container_name: flux_backend
    env_file:
      - ../config/environments/development.env
    ports:
      - "8000:8000"
    depends_on:
      - db

  frontend:
    build:
      context: ../src/frontend
      dockerfile: Dockerfile
    container_name: flux_frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:8000

  db:
    image: postgres:13
    container_name: flux_db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  prometheus:
    image: prom/prometheus
    container_name: flux_prometheus
    volumes:
      - ../src/monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana
    container_name: flux_grafana
    ports:
      - "3001:3000"
    volumes:
      - grafana_data:/var/lib/grafana

volumes:
  postgres_data:
  grafana_data:
