version: "3.9"
services:
  app:
    environment:
      - ENVIRONMENT=${ENVIRONMENT}
      - DATABASE_URL=${DATABASE_URL}_${ENVIRONMENT}
    container_name: app_${ENVIRONMENT}
    ports:
      - "8080:8080"

  database:
    container_name: db_${ENVIRONMENT}
    environment:
      - POSTGRES_DB=${DATABASE_NAME}_${ENVIRONMENT}
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
